### PR TITLE
wip will update views.py and updated requirements and readme

### PR DESCRIPTION
**Pull request by dzheng256**
to make things clearer

### CODE REVIEW

**Comment by dzheng256** [comment]
will finish soon

**Comment by azharichenko** [comment]
We don't need the `flask_cors` package, `flask-restful` takes care of that.

**Comment by dzheng256** [comment]
@azharichenko ok ill change after your PR gets merged

**Comment by RitwikGupta** [comment]
Closed due to #9! Open a new PR after pulling new changes.

**Pull request closed without merging**
