### PR TITLE
WIP adding other apis

### PR DESCRIPTION
**Pull request by dzheng256**
need to figure out a good way to add textbooks..

### CODE REVIEW

**Review by RitwikGupta — CHANGES_REQUESTED** [review]
Don't include swap files in your commit! Add `*.swp` to the .gitignore and run a `git rm -f *.swp` to get rid of tracked swap files.

**Comment by dzheng256** [comment]
oops, deleted

**Comment by RitwikGupta** [comment]
Is this still a WIP?

**Comment by dzheng256** [comment]
@RitwikGupta yeah

**Comment by dzheng256** [comment]
@RitwikGupta for something like the news API, is it necessary to have multiple urls for different combinations of inputs? Or is what I have right now fine? 
Like NewsAPI right now is
```
def get(self, feed, max_news_items):
        try:
            max_news_items = int(max_news_items)
            return news.get_news(feed, max_news_items)
```
with the url
`/news/<feed>/<max_news_items>`.
Should I create something like NewsDefaultFeedAPI that looks like
```
def get(self, feed='main_news', max_news_items):
        try:
            max_news_items = int(max_news_items)
            return news.get_news(feed, max_news_items)
```
with the url 
`/news/<max_news_items>` or is this not necessary? 
I also created TextbookNoTermAPI and TextbookAPI just to allow for two urls, but I eally feel like the noterm one is unecessary.

**Comment by RitwikGupta** [comment]
What you have is fine!

**Review by RitwikGupta — APPROVED** [review]

**Pull request merged**
